export const POST_LIST_REQUEST = "POST_LIST_REQUEST";
export const POST_LIST_SUCCESS = "POST_LIST_SUCCESS";
export const POST_LIST_FAIL = "POST_LIST_FAIL";

export const LIKE_UPDATE_REQUEST = "LIKE_UPDATE_REQUEST";
export const LIKE_UPDATE_SUCCESS = "LIKE_UPDATE_SUCCESS";
export const LIKE_UPDATE_FAIL = "LIKE_UPDATE_FAIL";
export const LIKE_UPDATE_RESET = "LIKE_UPDATE_RESET";
